export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white p-6">
      <div className="mx-auto max-w-4xl space-y-8">
        <h1 className="text-4xl font-semibold">Privacy Policy</h1>
        <p className="text-slate-300">
          HereFound is committed to protecting the privacy and data of users who report potential violations through Instagram. This page explains how we collect, use, store, and share data when integrating with Meta products and our services.
        </p>

        <section className="rounded-lg border border-slate-700 bg-slate-900 p-6">
          <h2 className="text-2xl font-semibold mb-3">What We Collect</h2>
          <ul className="list-disc space-y-2 pl-5 text-slate-300">
            <li>Instagram report metadata such as the reporter username and the shared Reel URL.</li>
            <li>Deepfake and IT Act analysis results generated by our AI engine.</li>
            <li>Content required to reply to users via the Meta Graph API when using DMs or comment mentions.</li>
          </ul>
        </section>

        <section className="rounded-lg border border-slate-700 bg-slate-900 p-6">
          <h2 className="text-2xl font-semibold mb-3">How We Use Data</h2>
          <ul className="list-disc space-y-2 pl-5 text-slate-300">
            <li>To analyze reported Instagram Reels for manipulated content and compliance with Indian IT Act provisions.</li>
            <li>To store flagged reports in Supabase for access by authorized organizations.</li>
            <li>To return a formatted cyber police complaint draft when a violation is found.</li>
            <li>To send response messages back through the Meta Graph API for DMs and mentions.</li>
          </ul>
        </section>

        <section className="rounded-lg border border-slate-700 bg-slate-900 p-6">
          <h2 className="text-2xl font-semibold mb-3">Meta Integration</h2>
          <p className="text-slate-300">
            HereFound uses Meta's Instagram Graph API and Webhooks to receive reports, process mentions, and send replies. We only use the access tokens and permissions required to process reports, read comments, and send messages related to reported content.
          </p>
        </section>

        <section className="rounded-lg border border-slate-700 bg-slate-900 p-6">
          <h2 className="text-2xl font-semibold mb-3">Data Storage</h2>
          <p className="text-slate-300">
            Reported data is stored in Supabase PostgreSQL. The `flagged_violations` data is protected with Row Level Security policies so each organization can only access its own reports.
          </p>
        </section>

        <section className="rounded-lg border border-slate-700 bg-slate-900 p-6">
          <h2 className="text-2xl font-semibold mb-3">Your Rights</h2>
          <p className="text-slate-300">
            If you are a reporter, you may request information on how your report was processed or ask for data correction. For privacy questions, please contact the HereFound team through the site administrator or via the organization responsible for the integration.
          </p>
        </section>

        <section className="rounded-lg border border-slate-700 bg-slate-900 p-6">
          <h2 className="text-2xl font-semibold mb-3">No Unnecessary Sharing</h2>
          <p className="text-slate-300">
            We do not sell user data. Reported information is only shared with authorized organizations and used to support the compliance review workflow.
          </p>
        </section>
      </div>
    </main>
  );
}
