import os
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, HttpUrl
import yt_dlp
import google.generativeai as genai

load_dotenv()

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-1.5-pro-latest')

if not GOOGLE_API_KEY:
    raise RuntimeError('GOOGLE_API_KEY is required')

genai.configure(api_key=GOOGLE_API_KEY)

SYSTEM_PROMPT = """You are a strict Indian cyber-law enforcement AI and digital forensics analyst. Your job is to detect violations and AI-generated content in videos. You MUST flag violations when evidence is present — do NOT be lenient or give the benefit of the doubt.

=== TASK 1: LEGAL VIOLATION DETECTION ===
Flag as a violation (is_violation: true) if the video contains ANY of the following:

DEEPFAKES & MANIPULATED CONTENT (IT Act Section 66C / 66D / 66E):
- A real person's face or voice replaced/cloned using AI or software
- Lip movements that do not match the audio (dubbing mismatch indicating manipulation)
- A public figure, celebrity, politician, or athlete saying or doing something they clearly did not say or do
- Voice cloning — the voice sounds synthetic, unnaturally smooth, or robotic
- Digitally altered facial expressions to change meaning of speech
- Any disclaimer like "AI generated", "deepfake", "voice cloned", "synthetic" visible in the video

ILLEGAL GAMBLING PROMOTION (IT Act Section 67 / IGPA):
- Promotion of betting apps, gambling websites, or fantasy sports with real money that are not registered in India (e.g., Fairplay, Parimatch, 1xBet, Bet365, etc.)
- Overlay of gambling promo codes, affiliate links, or QR codes for betting sites
- Influencer or celebrity promoting offshore gambling platforms directly or subtly
- Audio/text saying "bet now", "win real money", "use code [X] for bonus", etc. linked to gambling

=== TASK 2: AI GENERATION DETECTION ===
Flag as AI generated (is_ai_generated: true) if ANY of the following are visible:
- Faces that look unnaturally smooth, waxy, or plastic
- Eyes that blink at wrong times, are asymmetric, or look glassy
- Hair, fingers, or teeth with subtle distortions or extra/missing features
- Backgrounds that flicker, shift, or have inconsistent lighting/shadows
- Unnatural or jerky body movements or head pose inconsistencies
- Voice that sounds synthesized (TTS), lacks natural prosody, or has robotic undertones
- Visible "AI art" style, blurring at edges, or morph artifacts
- Any on-screen text indicating AI generation (e.g., "generated by", "AI avatar", etc.)

=== IMPORTANT RULES ===
- Be STRICT. If there are signs of any violation or AI generation, flag it. A confidence of 40%+ is enough to flag.
- Do NOT give the benefit of the doubt. If something LOOKS manipulated, it IS manipulated.
- If the video appears to be a normal human recording with no manipulation, then is_violation: false and is_ai_generated: false is acceptable.

=== OUTPUT FORMAT ===
Respond with ONLY this exact JSON object and NOTHING else — no markdown, no code fences, no explanation:
{"is_violation": boolean, "violation_type": "string describing the specific violation found, or null if none", "it_act_section": "e.g. Section 66D of IT Act 2000, or null", "confidence": integer 0-100, "is_ai_generated": boolean, "ai_generation_confidence": integer 0-100, "cyber_police_draft": "3-sentence formal complaint to National Cyber Crime Reporting Portal if is_violation is true, else null"}"""

class AnalyzeRequest(BaseModel):
    reel_url: HttpUrl

@app.post('/analyze')
async def analyze(request: AnalyzeRequest):
    import uuid
    import time
    file_path = f"/tmp/{uuid.uuid4()}.mp4"
    uploaded_file = None
    try:
        ydl_opts = {
            'quiet': True, 
            'format': 'best', 
            'noplaylist': True,
            'outtmpl': file_path
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.extract_info(str(request.reel_url), download=True)
            
        if not os.path.exists(file_path):
            raise HTTPException(status_code=422, detail='Failed to download the video')

        uploaded_file = genai.upload_file(path=file_path)
        
        while uploaded_file.state.name == "PROCESSING":
            time.sleep(2)
            uploaded_file = genai.get_file(uploaded_file.name)
            
        if uploaded_file.state.name == "FAILED":
            raise ValueError("Gemini failed to process the uploaded video file.")

        model = genai.GenerativeModel(GEMINI_MODEL)
        response = model.generate_content(
            contents=[SYSTEM_PROMPT, uploaded_file]
        )

        raw_text = response.text or ''

        # The Gemini response must be strict JSON. If there is any extra text, try to parse JSON block.
        import json
        text = raw_text.strip()
        if text.startswith('﻿'):
            text = text[1:]

        try:
            result = json.loads(text)
        except json.JSONDecodeError:
            # Fallback: try to locate JSON substring.
            import re
            match = re.search(r'{.*}', text, re.S)
            if match:
                result = json.loads(match.group(0))
            else:
                raise

        print('=== ANALYSIS REPORT ===')
        print(f"Reel URL: {request.reel_url}")
        print(f"Status: {'🚨 VIOLATION' if result.get('is_violation') else '✅ CLEAN'}")
        print(f"Violation Type: {result.get('violation_type', 'N/A')}")
        print(f"IT Act Section: {result.get('it_act_section', 'N/A')}")
        print(f"Confidence: {result.get('confidence', 'N/A')}%")
        print(f"AI Generated: {'🤖 YES' if result.get('is_ai_generated') else '👤 NO'} (confidence: {result.get('ai_generation_confidence', 'N/A')}%)")
        print('=======================')
        return result
    except Exception as exc:
        import traceback
        import sys
        print(f"AI Engine Analysis Error occurred: {exc}", file=sys.stderr)
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"AI Engine Error: {str(exc)}")
    finally:
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except:
                pass
        if uploaded_file:
            try:
                genai.delete_file(uploaded_file.name)
            except:
                pass
