import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const { messages, reportContext } = await req.json();

    const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;
    if (!GOOGLE_API_KEY) {
      return NextResponse.json({ reply: 'Google API key not configured.' }, { status: 500 });
    }

    // Build conversation history for Gemini
    const systemInstruction = `You are HereFound AI Assistant — a knowledgeable cyber-law expert specializing in Indian IT Act (2000) and IT Rules (2021). 
You help users understand violation reports generated by the HereFound automated compliance system.

CURRENT REPORT CONTEXT:
${reportContext}

Answer concisely and helpfully. Explain legal terms in plain language. If asked about the complaint draft, provide guidance on how to file it. Keep responses under 150 words unless a detailed explanation is necessary.`;

    const contents = messages.map((m: { role: string; content: string }) => ({
      role: m.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: m.content }],
    }));

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${GOOGLE_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: systemInstruction }] },
          contents,
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 512,
          },
        }),
      }
    );

    const data = await response.json();
    const reply = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? 'Sorry, I could not generate a response.';

    return NextResponse.json({ reply });
  } catch (err) {
    console.error('Chat API error:', err);
    return NextResponse.json({ reply: 'An error occurred. Please try again.' }, { status: 500 });
  }
}
